### ISSUE TITLE
Joining a scheduling link twice at the same time ends up with 2 different calls

### ISSUE THREAD

**Issue by maxwofford** [hackclub/slash-z#10]
Haven't confirmed yet, but Gary & Mel encountered something like this from an event that Gary scheduled

**Comment by garyhtou** [comment]
Mel had scheduled a `/z` meeting. When I joined, it seems like I was placed into a different call than Mel.

### `/z` Zoom Call Info

https://hack.af/z?id=1gve2a
![Zoom Call Details](https://user-images.githubusercontent.com/20099646/111016336-18245500-8362-11eb-9046-5e31f628d305.png)


### After leaving the call and attempting to rejoin, I got this:

![image (25)](https://user-images.githubusercontent.com/20099646/111016377-63d6fe80-8362-11eb-97fb-1de27d04cb68.png)

**Comment by maxwofford** [comment]
I looked at the logs -- seems like they joined the same link within a second of eachother & ran into a race condition

**Comment by maxwofford** [comment]
I think this was fixed in #30
