### ISSUE TITLE
Retarget email notifications from zoom admin account

### ISSUE THREAD

**Issue by grymmy** [hackclub/slash-z#110]
Right now the zoom admin account sends warning notifications only to max@hackclub.com.

We should instead have it notify [infra@hackclub.com](https://groups.google.com/a/hackclub.com/g/infra)

**Comment by grymmy** [comment]
@zachlatta any chance we could get your assistance in adding zoom email notifications target infra@hackclub.com?  It also probably make sense for myself and @JosiasAurel to become zoom "admins"...

**Comment by maxwofford** [comment]
I also looked into redirecting notifications to "infra@". Zoom doesn't have a setting for this –it will only send alert emails to admins and owners on the account– so the only think I can do on my side is setup an email redirect.

**Comment by grymmy** [comment]
Looked over @zachlatta 's shoulder as he added myself and Josias as admin users.  Also added infra@hackclub.com to zoom's user list (whether or not this'll actually result in emails successfully being sent there, I guess we'll see...)
