### ISSUE TITLE
Start meetings in threads

### ISSUE THREAD

**Issue by maxwofford** [hackclub/slash-z#13]
![image](https://user-images.githubusercontent.com/5891442/111873685-df8b0980-8967-11eb-9914-f71ae45ebe32.png)

**Comment by YodaLightsabr** [comment]
I think this would be a really good idea, but the issue with global shortcuts is that they don't provide the context of where they were run, so you don't know what channel to respond in. I also don't think that it's possible to send ephemeral messages in global shortcuts :/ (see [https://stackoverflow.com/questions/68491115/slack-ephemeral-message-from-global-shortcut](https://stackoverflow.com/questions/68491115/slack-ephemeral-message-from-global-shortcut))
