### ISSUE TITLE
Ephemeral Messages

### ISSUE THREAD

**Issue by P1xelC0da** [hackclub/slash-z#137]
Instead of slash-z sending ephemeral messages with the "claim host" code, it should send the code to your DMs.

**Comment by P1xelC0da** [comment]
Tbh, I might end up looking at the API docs for Slack and submitting a PR for this. It'd be a cool thing to add, since closing out of the ephemeral messages is a muscle memory thing of sorts for me. Although, I have a philosophy of: If it isn't Discord, then don't touch it. - I'm sure this'll be a learning experience for me.

**Comment by JosiasAurel** [comment]
@P1xelC0da in what situation would this change be helpful to you?

**Comment by P1xelC0da** [comment]
I mentioned this in the reply above.
> It'd be a cool thing to add, since closing out of the ephemeral messages is a muscle memory thing of sorts for me.

**Comment by grymmy** [comment]
@P1xelC0da - have no issue with this feature implemented, myself, but please make it opt-in and disabled by default to not affect others who may be used to (and are fine w/) the current flow that gives you in-context info.  if you feel strongly that this new flow should be the default, I think I need more convincing tbh - why is it better by definition to DM this info?

**Comment by P1xelC0da** [comment]
It can 100% opt-in for slash-z users. But the ephemeral messages (imo) can be lost, and for posterity purposes can be sent to DMs. I'll check out the API docs to see how I can do this. I'm not sure how to make something "opt-in" on Slack.

**Comment by grymmy** [comment]
TBH when I was writing that above, I actively was thinking of adding some sort of custom configs into /z, i.e. `/z set <name> <value>`.  This could allow for lots of fun little playful hacking while at the same time protecting users that just need stable and predictable zoom experiences...  also could be useful for debugging purposes too

**Comment by P1xelC0da** [comment]
Yeah that'd work honestly.

**Comment by JosiasAurel** [comment]
there's a new feature in /z allowing you to get the host code using `/z-code <meetingID>` since #203
