### ISSUE TITLE
Slack call status out of date

### ISSUE THREAD

**Issue by maxwofford** [hackclub/slash-z#15]
<img width="1179" alt="Screen Shot 2021-03-27 at 01 00 28" src="https://user-images.githubusercontent.com/5891442/112710506-2319d200-8e98-11eb-92f7-ec8be3e88545.png">

This is happening when Zoom fails to send us a webhook of a user join/leave event. I've seen this pretty commonly (either Zoom delays up to 30 minutes, or just never sending the request), so this is probably a good thing to handle.

**Comment by maxwofford** [comment]
Not sure what changed, but Zoom has gotten much better at sending consistent webhooks. I'm marking this as an enhancement b/c we can probably be a _bit_ more quick to update (ie. if the server restarts while zoom sends a `participant_joined`) by querying the participants of open calls every few seconds. I don't consider this a bug anymore though.

**Comment by grymmy** [comment]
@JosiasAurel Can you please try to reproduce this issue to see if it still exists?

**Comment by JosiasAurel** [comment]
can't reproduce this issue
