### ISSUE TITLE
Home page erroring (need to investigate)

### ISSUE THREAD

**Issue by maxwofford** [hackclub/slash-z#16]
<img width="387" alt="Screen Shot 2021-03-29 at 10 54 20" src="https://user-images.githubusercontent.com/5891442/112855779-24f0ba80-907d-11eb-91cd-cd69c0fb5fa4.png">

Checking the logs, it looks like they opened the meeting link (generating a meeting) & left. A second meeting was generated from visiting the meeting link a minute later. This page was loaded in between the 2 meetings:
<img width="378" alt="Screen Shot 2021-03-29 at 10 55 52" src="https://user-images.githubusercontent.com/5891442/112855987-5cf7fd80-907d-11eb-8930-62d17330e02d.png">

I'll add more details once I learn them, but keeping the title ambiguous for now

**Comment by maxwofford** [comment]
I wonder if this has to do with some race conditions caused by #10 (at time of writing i'm not locking schedule link opens). I wonder if one of the airtable formulas I'm using breaks when there are multiple open meetings?

**Comment by JosiasAurel** [comment]
can't reproduce this issue. please re-open if you encounter this again
