### ISSUE TITLE
Majority of requests to slash-z result in 404's

### ISSUE THREAD

**Issue by grymmy** [hackclub/slash-z#168]
![Screenshot 2023-09-08 at 1 25 59 PM](https://github.com/hackclub/slash-z/assets/43505167/80d3470d-26af-4c6f-a125-a5f1828b5c8a)
I believe this is just as a result of certain webhook events that we don't handle yet, but it would be good to clean these up to get things to the state where successful (200-range) traffic is the overwhelming majority such that we can more easily detect new anomalies/issues relating to errors in the future.

**Comment by JosiasAurel** [comment]
majority is now 200 which I think is thanks to #165 
<img width="403" alt="image" src="https://github.com/hackclub/slash-z/assets/47951376/f59377f1-e71a-4319-8c23-77f086eb5ebc">

**Comment by grymmy** [comment]
I have solved this via dashboard magic - we now show 200/302/415's combined as "OK", and then also show the raw http codes separately.  Thus we can quickly confirm that everything looks nominal at a glance, but can also see the raw data.
<img width="1113" alt="Screenshot 2023-10-16 at 9 32 32 AM" src="https://github.com/hackclub/slash-z/assets/43505167/26ffc445-ed80-46de-812c-66a5982e66ca">

**Comment by JosiasAurel** [comment]
awesome
