### ISSUE TITLE
Investigate delete_meeting errors

### ISSUE THREAD

**Issue by grymmy** [hackclub/slash-z#169]
We occasionally get meeting deletion errors.
![Screenshot 2023-09-08 at 1 28 26 PM](https://github.com/hackclub/slash-z/assets/43505167/db4939d2-f8f9-488c-a307-2619f0c815c4)
![Screenshot 2023-09-08 at 1 29 22 PM](https://github.com/hackclub/slash-z/assets/43505167/86737c0b-a77e-44b6-bb9e-b11446daae4c)

What does it mean when these happen?  Is this a serious issue?  Should it be reported as an actual error?

**Comment by grymmy** [comment]
In that case we are not really in an error state, right?  So should it be reported as an error when it is not?  Could be a warning instead

**Comment by grymmy** [comment]
@JosiasAurel per my comment above, do you agree we can remove this specific metric, as it doesn't seem to be indicative of an actual (practical) error?

**Comment by JosiasAurel** [comment]
> @JosiasAurel per my comment above, do you agree we can remove this specific metric, as it doesn't seem to be indicative of an actual (practical) error?

yes

**Comment by grymmy** [comment]
closing this as its a) old and b) not an error
