### ISSUE TITLE
Meeting gets deleted even if 1 person join and leave

### ISSUE THREAD

**Issue by EliusHHimel** [hackclub/slash-z#170]
In general when I schedule a normal Zoom call from my personal (which has a basic/free subscription with a 40-minute limit) account, and give the link to participants they often join and leave the call immediately just out of curiosity or to check if the link works, but the meeting does not get deleted. Even after the 40-minute limit is exceeded, people can join using the same link and it works perfectly. But when I used the `/z` command and tried joining and leaving the meeting I saw that I could not join again in the same meeting. I tried using the Google Calander Addon to schedule a meeting and the same thing happens for the scheduled meeting as well. It would be really great if the meeting remains joinable for at least 1 or 2 days.

**Comment by JosiasAurel** [comment]
Hey @EliusHHimel, links becoming invalid after everyone leaves the meeting is expected. Meetings created through Slack using /z will also become invalid after about two minutes if nobody joins. 

slash-z has a limited number of available Zoom licenses (20 in total, but can hold up to 40 meetings) that we use to accommodate all users from Slack and the Hack Club staff. If we leave a meeting to be valid for that long, we will easily run out of available licenses to use which will be problematic.
