### ISSUE TITLE
Zoom meetings that have finished still show "Join" button in slack

### ISSUE THREAD

**Issue by grymmy** [hackclub/slash-z#171]
<img width="885" alt="Screenshot 2023-09-09 at 8 28 45 PM" src="https://github.com/hackclub/slash-z/assets/43505167/1aa0b7a7-9f85-4336-95f2-521ba6d79edc">

**Comment by grymmy** [comment]
Note that image above is what slack showed after a completed zoom session (that I know for a fact slash-z received meeting.end webhook for

**Comment by JosiasAurel** [comment]
Solved since #175 

previously slash-z would not mark the slack call as ended because it will return prematurely when it gets a 400/404 event... even if we get a meeting.ended event from Zoom

that change ensures that if we get a meeting.ended event, it will mark the Slack call as closed
