### ISSUE TITLE
Meeting recordings are not accessible from app homepage

### ISSUE THREAD

**Issue by JosiasAurel** [hackclub/slash-z#178]
A few hack clubbers have tried to access their meeting recordings but there's no obvious way to do so. 

We should look into a way to make their meeting recordings accessible to them.

**Comment by BrightTheBackpack** [comment]
If they record locally they should be able to see it in the zoom home page

**Comment by JosiasAurel** [comment]
meeting recordings will be accessible through the /z app homepage for the meeting host.
for meeting you recorded on your computer, you should be able to choose where they're going to be stored on your computer 
![WhatsApp Image 2024-02-16 at 16 41 57](https://github.com/hackclub/slash-z/assets/47951376/7024b1e0-faa4-40e5-92e4-a01877e9b923)
