### ISSUE TITLE
Feature: Personal meeting rooms

### ISSUE THREAD

**Issue by YodaLightsabr** [hackclub/slash-z#185]
It would be cool to have personal meeting links for use in external services like Cron. This was discussed in #hq: https://hackclub.slack.com/archives/C0C78SG9L/p1701291606226089

This might look like a settings/configuration page in the Slash-Z app homepage, and the links could be customizable.

**Comment by grymmy** [comment]
This feature is not comprehensively proposed here in an actionable way - as a result I am closing it.  Feel free to re-open the issue and update the description with **specific details** (i.e. a concrete proposal) on how exactly this feature would function.
