### ISSUE TITLE
ssl certificate expiring 05/08/2024

### ISSUE THREAD

**Issue by grymmy** [hackclub/slash-z#198]
![Screenshot 2024-05-01 at 2 20 57 PM](https://github.com/hackclub/slash-z/assets/43505167/b6295150-a370-4b8a-82de-ebeb3da4f171)

Guessing this will cause prod to go down if we don't fix this preemptively

**Comment by JosiasAurel** [comment]
That is not the domain used by slash-z on the Heroku app. 

iirc we created that domain to point to a version of slash-z on DigitalOcean in the recent incident before moving back to Heroku. 

<img width="1257" alt="Screenshot 2024-05-02 at 09 13 23" src="https://github.com/hackclub/slash-z/assets/47951376/d10de454-32e3-42cc-a62d-8b65e9b77de9">
