### ISSUE TITLE
Unclear how to get host key from scheduled meeting

### ISSUE THREAD

**Issue by maxwofford** [hackclub/slash-z#21]

**Comment by bellesea** [comment]
does https://zguide.hackclub.com/chapters/2_1_app_home.html solve this issue?

**Comment by maxwofford** [comment]
I think the case I'm thinking of is if I'm a user and i just scheduled a meeting & I want to know how to get the host key. I think that documents it, but let's link users to it after scheduling a meeting.

**Comment by YodaLightsabr** [comment]
Would /z send the user a DM telling them how to get it on their first scheduled meeting?

**Comment by grymmy** [comment]
It seems to me that if we have gone this long without resolving this issue, it is likely unimportant.  I am closing this issue, if you feel strongly about advocating for its fix, please reopen it with your argument(s).
