### ISSUE TITLE
Check support for waiting rooms

### ISSUE THREAD

**Issue by maxwofford** [hackclub/slash-z#22]
![image](https://user-images.githubusercontent.com/5891442/117665396-c84ee800-b170-11eb-89d4-5962fee877d6.jpeg)

**Comment by YodaLightsabr** [comment]
If we know for sure that there isn't a setting to enable it, but turn it off by default, I'll move forward with the Virtual Lobby thing.

**Comment by grymmy** [comment]
Given we are a) not looking for perfect feature parity to zoom pro and b) since this feature has been unimplemented for 2 years, I am closing issue as wontfix.

If you feel strongly about this feature and would like to advocate for its implementation, please reopen it and ping me.
