### ISSUE TITLE
Slash Z Clogs Up Airtable

### ISSUE THREAD

**Issue by sampoder** [hackclub/slash-z#29]
The Airtable pruning done by Slash Z was not enough to prevent us being stuck at 50,000 records. We had old web hook records from February still being held.

I have since manually deleted all web hook events that were a day old. This wasn't the perfect solution, and I did make a backup in case but it was an emergency bandaid. I'll monitor whether this bandaid is tainted and it infects the app (AKA if I made a mistake). I'll also send this backup to @maxwofford on Slack.

I'm not entirely sure what is causing this issue at the moment. It could be the pruning script, or it could be job running issues.

**Comment by maxwofford** [comment]
Closed b/c we're now using prisma!+!!1! https://github.com/hackclub/slash-z/commit/456f25fed7e81c8ed92c522ca5044aaab6fd2453

**Comment by sampoder** [comment]
YEAH!!!
