### ISSUE TITLE
An error appears after about 2 minutes of the call starting claiming the host has ended the meeting 

### ISSUE THREAD

**Issue by ItsTobez** [hackclub/slash-z#44]
After running /z and staying on the call for approximately 2 minutes, I get an error saying the host has ended the meeting. However, I am the only one on the call and have not ended the meeting.

**Comment by praveenscience** [comment]
And it is the same when there are three people with one participant, one host and one co-host as well! 😢

**Comment by maxwofford** [comment]
This looks like it's caused by [this api request](https://github.com/hackclub/slash-z/blob/cc3a9462c040fef21bdc260b5370f1f5e19f1308/api/close-zoom-call.js#L19) failing.

Not sure, but we might want to also search for calls reported as previously opened too ([referenced here](https://devforum.zoom.us/t/api-metrics-meetings-meetingid-participants-participantid-qos/44924/2))

**Comment by maxwofford** [comment]
When I opened a zoom meeting and checked the stats on it, I got "The meeting does not exist"

<img width="1241" alt="Screen Shot 2022-02-19 at 12 58 04" src="https://user-images.githubusercontent.com/5891442/154813139-3b0fa5ee-f990-4e1d-92e4-4b9c2437a230.png">

Weird thing is [the documentation](https://marketplace.zoom.us/docs/api-reference/zoom-api/methods/#operation/dashboardMeetingDetail) says we'd only be getting this response if the call doesn't exist (not an api failure or settings issue)

<img width="532" alt="Screen Shot 2022-02-19 at 12 59 33" src="https://user-images.githubusercontent.com/5891442/154813130-55cd8024-3136-4f73-9ada-814d2d953a72.png">

**Comment by praveenscience** [comment]
@maxwofford But seems like this got fixed using [cc3a946](https://github.com/hackclub/slash-z/commit/cc3a9462c040fef21bdc260b5370f1f5e19f1308)?

**Comment by maxwofford** [comment]
@praveenscience cc3a9462c040fef21bdc260b5370f1f5e19f1308 is a good stopgap for now, but expanding the 2 hour time means you'll get kicked out of meetings after 2 hours, and all our hosts will fill up (because we only check every 2 hours if we can close a meeting)

**Comment by praveenscience** [comment]
Okay, got it... But whatever it is, it's gonna close irrespective of it being stale! 😑

**Comment by maxwofford** [comment]
<img width="1049" alt="Screen Shot 2022-02-19 at 13 11 00" src="https://user-images.githubusercontent.com/5891442/154813483-eacba97d-f4a7-4429-aa61-a2a8f8468f55.png">

Zoom's own dashboard doesn't show an active call across all our accounts either.

**Comment by praveenscience** [comment]
Oh I just saw the comments in slack. Thanks. Need any help to fix? Where do I start?

**Comment by maxwofford** [comment]
I'm not really sure where to go from here... slash-z can't properly manage meetings if zoom itself isn't reporting meetings on our account correctly. Maybe we should start putting up a notice that it doesn't work right now?

**Comment by maxwofford** [comment]
Funny, the meetings are now showing up under the "ended" category:
<img width="774" alt="Screen Shot 2022-02-19 at 13 40 13" src="https://user-images.githubusercontent.com/5891442/154814462-4782a1cb-2c39-4608-89e4-fbbf02887d63.png">

**Comment by maxwofford** [comment]
<img width="490" alt="Screen Shot 2022-02-19 at 13 40 57" src="https://user-images.githubusercontent.com/5891442/154814483-4ef790f5-21a6-40ad-8510-5def7572416d.png">

Zoom also isn't sending us webhook events for meetings either.

**Comment by ItsTobez** [comment]
I'm sure you're already aware of this, but zoom has recently updated their API, apparently there has been a change to the meeting minute calculation. This seems it could be relevant to this issue. Here's a link to the chanelog: https://marketplace.zoom.us/docs/guides/stay-up-to-date/changelog/

**Comment by praveenscience** [comment]
Yep, Zoom introduced breaking changes to their APIs from today!

**Comment by maxwofford** [comment]
@ItsTobez I don't see anything in the [changelog posted 4 days ago](https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/dashboard-api-meeting-minute-calculation-change) related to this. What's the change?

**Comment by ItsTobez** [comment]
After looking into it, it doesn't seem particularly related to the issue. Sorry about that.

**Comment by maxwofford** [comment]
Can confirm the issues on the dashboard aren't showing up anymore:

<img width="309" alt="Screen Shot 2022-02-21 at 19 47 05" src="https://user-images.githubusercontent.com/5891442/155043413-46205974-c4a0-4c36-a81d-5f76a3549d21.png">
