### ISSUE TITLE
Warning/confirmation for new users running /z in public channels

### ISSUE THREAD

**Issue by cosmicoptima** [hackclub/slash-z#48]
New members sometimes don't realize that running /z in a given channel gives everyone in said channel access to the meeting. This might occur less often if, upon running /z for the first time, the user is shown a disclaimer explaining how /z works. (And probably some form of interaction is required before starting the call / the user is allowed to cancel)

**Comment by grymmy** [comment]
This issue seems to be fixed in the issue mentioned above (#49).
