### ISSUE TITLE
Home included private channels

### ISSUE THREAD

**Issue by YodaLightsabr** [hackclub/slash-z#55]
The slash-z home includes private channels, which show up as undefined.

![](https://yodacode.xyz/Fb5a8730d94.png)

**Comment by maxwofford** [comment]
additional context on this in [slack](https://hackclub.slack.com/archives/C0179FFFRRV/p1651118353736509)

seems like it could be related to [this line](https://github.com/hackclub/slash-z/blob/188929e8a482bb700dbf7495f66c3606d1ac395e/api/is-public-slack-channel.js#L19) only checking `is_private`. [Slack's docs](https://api.slack.com/methods/conversations.info) also mention...

- `is_mpim`
- `is_im`
- `is_group`

Just a hunch from checking the docs, none of this is tested!

**Comment by YodaLightsabr** [comment]
I think we should just check if it's a public channel and not a DM/group DM, instead of listing all of the user's possible private channels/DM channels that have meetings.
