### ISSUE TITLE
Rotate all API keys after Heroku security breach

### ISSUE THREAD

**Issue by sampoder** [hackclub/slash-z#57]
These need to be rotated:

- [ ] AIRBRIDGE_API_KEY
- [ ] BUGSNAG_API_KEY
- [ ] DATABASE_URL
- [ ] PAPERTRAIL_API_TOKEN
- [ ] SLACK_BOT_USER_OAUTH_ACCESS_TOKEN
- [ ] SLACK_CLIENT_ID
- [ ] SLACK_CLIENT_SECRET
- [ ] ZOOM_VERIFICATION_TOKEN

**Comment by grymmy** [comment]
@sampoder Given this happened nearly a year ago, I assume this work was completed.  Please reopen this issue if that is not the case.
