### ISSUE TITLE
1000 Zoom Participants

### ISSUE THREAD

**Issue by kenyue102008** [hackclub/slash-z#77]
Hi, Good (*morning, lunch, evening, night, mid-night...) Developer, I saw a sentence you mention that you can only manage to get 300 participants only due to zoom, but I've found a plan to get 100 participants, can you check it out

https://explore.zoom.us/en/contactsales/
<img width="203" alt="Ảnh chụp Màn hình 2022-08-23 lúc 5 44 26 CH" src="https://user-images.githubusercontent.com/92426087/186139011-06f45888-39a1-4018-a132-776a700e9f94.png">

**Comment by maxwofford** [comment]
Hey @kenyue102008! Unfortunately we don't have access to Zoom One Advanced Enterprise– I've called them about this before.

**Comment by kenyue102008** [comment]
> Hey @kenyue102008! Unfortunately we don't have access to Zoom One Advanced Enterprise– I've called them about this before.

You can try to use the paid version of google meet, it's better than zoom, you can also try using cisco webex!
