### ISSUE TITLE
Discord bot

### ISSUE THREAD

**Issue by sbtacademy** [hackclub/slash-z#84]
I love your project so much! Can you please code a bot for discord too so we can add to our own server! Thank you!!! :D

**Comment by sampoder** [comment]
Hey @sbtacademy! Love to hear that Slash Z has been working well for you :D. We likely can't host a Discord version of our bot as we want to keep access relatively locked down. That said, if you've got a couple of Zoom Pro accounts spare, the code is fairly modular so you could probably fork it, modify it to use something like discord.js and then host your own for your server. Happy to help you sift through the code if you'd like!

**Comment by grymmy** [comment]
Per @sampoder 's comment above, we do not plan on implementing this functionality.  Closing this issue now, if you feel strongly about this, and would like to advocate further for this feature, please reopen this issue.
